version: "2"
services:
  tests:
    build:
        context: ./tests
    links:
      - fpm
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./application:/var/application
      expose:
          - "9000"